export enum ZnsTemplateType {
  ORDER_CONFIRMATION = 'ORDER_CONFIRMATION',
  ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  TICKET_BOOKING_SUCCESS = 'TICKET_BOOKING_SUCCESS',
  TICKET_REMINDER = 'TICKET_REMINDER',
  PRICE_REQUEST_RECEIVED = 'PRICE_REQUEST_RECEIVED',
  PRICE_REQUEST_RESPONSE = 'PRICE_REQUEST_RESPONSE',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  PROMOTIONAL_MESSAGE = 'PROMOTIONAL_MESSAGE',
  USER_VERIFICATION = 'USER_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
} 