services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    depends_on:
      - frontend
    networks:
      - app-network
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro


  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:4201"
    env_file:
      - apps/frontend/.env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-3333}:3333"
    env_file:
      - apps/backend/.env
    environment:
      - NODE_ENV=production
      # Add other environment variables as needed
      # - DATABASE_URL=
      # - JWT_SECRET=
    volumes:
      # Mount necessary files for running migrations
      - ./libs:/app/libs
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
    networks:
      - app-network

  migration:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.migration
    env_file:
      - apps/backend/.env
    volumes:
      - ./libs:/app/libs
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
