import { UserService } from '../../user/services/user.service';
import { UserAdminService } from '../../user/services/admin/user-admin.service';
import { PostFrontendService } from '../../post/frontend/services/post-frontend.service';
import { PostAdminService } from '../../post/admin/services/post-admin.service';
import { ProfileService } from '../../profile/services/profile.service';
import { SettingsAdminService } from '../../settings/admin/services/settings-admin.service';
import { SettingsFrontendService } from '../../settings/frontend/services/settings-frontend.service';
import { SeoAdminService } from '../../seo/admin/services/seo-admin.service';
import { SeoFrontendService } from '../../seo/frontend/services/seo-frontend.service';
import { FooterAdminService } from '../../footer/admin/services/footer-admin.service';
import { FooterFrontendService } from '../../footer/frontend/services/footer-frontend.service';
import { CategoryFrontendService } from '../../category/frontend/services/category-frontend.service';
import { CategoryAdminService } from '../../category/admin/services/category-admin.service';
import { ServiceAdminService } from '../../service/admin/services/service-admin.service';
import { ServiceFrontendService } from '../../service/frontend/services/service-frontend.service';
import { ProductAdminService } from '../../product/admin/services/product-admin.service';
import { ProductFrontendService } from '../../product/frontend/services/product-frontend.service';
import { CrossSellService } from '../../product/frontend/services/cross-sell.service';
import { ProductSpecificationService } from '../../product/services/product-specification.service';
import { ProductComboService } from '../../product/frontend/services/product-combo.service';
import { ProductStockHistoryService } from '../../product/services/product-stock-history.service';
import { PriceRequestService } from '../../price-request/services/price-request.service';
import { FeatureFlagsAdminService } from '../../feature-flags/admin/services/feature-flags-admin.service';
import { FeatureFlagsFrontendService } from '../../feature-flags/frontend/services/feature-flags-frontend.service';
import { HeroService } from '../../hero/admin/services/hero.service';
import { HeroSliderService } from '../../hero/admin/services/hero-slider.service';
import { HeroVideoService } from '../../hero/services/hero-video.service';
import { ThemeAdminService } from '../../theme/admin/services/theme-admin.service';
import { ThemeFrontendService } from '../../theme/frontend/services/theme-frontend.service';
import { ThemeSectionAdminService } from '../../theme/admin/services/theme-section-admin.service';
import { ComponentStyleConfigAdminService } from '../../theme/admin/services/component-style-config-admin.service';
import { ComponentStyleConfigFrontendService } from '../../theme/frontend/services/component-style-config-frontend.service';
import { LanguageFrontendService } from '../../language/frontend/services/language-frontend.service';
import { LanguageAdminService } from '../../language/admin/services/language-admin.service';
import { AboutAdminService } from '../../about/admin/services/about-admin.service';
import { AboutFrontendService } from '../../about/frontend/services/about-frontend.service';
import { LogoFrontendService } from '../../settings/frontend/services/logo-frontend.service';
import { LogoAdminService } from '../../settings/admin/services/logo-admin.service';
import { CustomerLogoFrontendService } from '../../customer-logo/frontend/services/customer-logo-frontend.service';
import { CustomerLogoAdminService } from '../../customer-logo/admin/services/customer-logo-admin.service';
import { AuthFrontendService } from '../../auth/frontend/services/auth-frontend.service';
import { AuthAdminService } from '../../auth/admin/services/auth-admin.service';
import { ContactAdminService } from '../../contact/admin/services/contact-admin.service';
import { ContactFrontendService } from '../../contact/frontend/services/contact-frontend.service';
import { GalleryFrontendService } from '../../gallery/frontend/services/gallery-frontend.service';
import { GalleryAdminService } from '../../gallery/admin/services/gallery-admin.service';
import { ContactSectionAdminService } from '../../contact/admin/services/contact-section-admin.service';
import { ContactSectionFrontendService } from '../../contact/frontend/services/contact-section-frontend.service';
import { TicketPricingSectionAdminService } from '../../ticket-pricing/admin/services/ticket-pricing-section-admin.service';
import { TicketPricingSectionFrontendService } from '../../ticket-pricing/frontend/services/ticket-pricing-section-frontend.service';
import { OrderTicketSectionAdminService } from '../../order-ticket/admin/services/order-ticket-section-admin.service';
import { OrderTicketSectionFrontendService } from '../../order-ticket/frontend/services/order-ticket-section-frontend.service';
import { FoodMenuFrontendService } from '../../food-menu/frontend/services/food-menu-frontend.service';
import { FoodMenuAdminService } from '../../food-menu/admin/services/food-menu-admin.service';
import { PaymentFrontendService } from '../../payment/frontend/services/payment-frontend.service';
import { PaymentAdminService } from '../../payment/admin/services/payment-admin.service';
import { OrderFrontendService } from '../../order/frontend/services/order-frontend.service';
import { OrderAdminService } from '../../order/admin/services/order-admin.service';
import { UploadFrontendService } from '../../upload/frontend/services/upload-frontend.service';
import { UploadAdminService } from '../../upload/admin/services/upload-admin.service';
import { SettingsService } from '../../settings/services/settings.service';
import { DashboardAdminService } from '../../dashboard/admin/services/dashboard-admin.service';
import { CommentAdminService } from '../../comment/admin/services/comment-admin.service';
import { CommentFrontendService } from '../../comment/frontend/services/comment-frontend.service';
import { AdminReviewService } from '../../review/admin/services/admin-review.service';
import { FrontendReviewService } from '../../review/frontend/services/frontend-review.service';
import { ISiteStatisticsAdminService, ISiteStatisticsFrontendService } from '../../site-statistics/interfaces/site-statistics-services.interface';
import { MailService } from '../../mail/services/mail.service';
import { AdminMenuAdminService } from '../../admin-menu/admin/services/admin-menu-admin.service';
import { AdminMenuFrontendService } from '../../admin-menu/frontend/services/admin-menu-frontend.service';

export interface ITrpcServices {
  userService: UserService;
  userAdminService: UserAdminService;
  postService: PostFrontendService;
  postAdminService: PostAdminService;
  profileService: ProfileService;
  settingsAdminService: SettingsAdminService;
  settingsFrontendService: SettingsFrontendService;
  seoAdminService: SeoAdminService;
  seoFrontendService: SeoFrontendService;
  footerAdminService: FooterAdminService;
  footerFrontendService: FooterFrontendService;
  categoryFrontendService: CategoryFrontendService;
  categoryAdminService: CategoryAdminService;
  serviceAdminService: ServiceAdminService;
  serviceFrontendService: ServiceFrontendService;
  productAdminService: ProductAdminService;
  productFrontendService: ProductFrontendService;
  crossSellService: CrossSellService;
  productSpecificationService: ProductSpecificationService;
  productComboService: ProductComboService;
  productStockHistoryService: ProductStockHistoryService;
  priceRequestService: PriceRequestService;
  featureFlagsAdminService: FeatureFlagsAdminService;
  featureFlagsFrontendService: FeatureFlagsFrontendService;
  heroService: HeroService;
  heroSliderService: HeroSliderService;
  heroVideoService: HeroVideoService;
  themeAdminService: ThemeAdminService;
  themeFrontendService: ThemeFrontendService;
  themeSectionAdminService: ThemeSectionAdminService;
  componentStyleConfigAdminService: ComponentStyleConfigAdminService;
  componentStyleConfigFrontendService: ComponentStyleConfigFrontendService;
  languageFrontendService: LanguageFrontendService;
  languageAdminService: LanguageAdminService;
  aboutAdminService: AboutAdminService;
  aboutFrontendService: AboutFrontendService;
  logoFrontendService: LogoFrontendService;
  logoAdminService: LogoAdminService;
  customerLogoFrontendService: CustomerLogoFrontendService;
  customerLogoAdminService: CustomerLogoAdminService;
  authFrontendService: AuthFrontendService;
  authAdminService: AuthAdminService;
  contactAdminService: ContactAdminService;
  contactFrontendService: ContactFrontendService;
  galleryFrontendService: GalleryFrontendService;
  galleryAdminService: GalleryAdminService;
  contactSectionAdminService: ContactSectionAdminService;
  contactSectionFrontendService: ContactSectionFrontendService;
  ticketPricingSectionAdminService: TicketPricingSectionAdminService;
  ticketPricingSectionFrontendService: TicketPricingSectionFrontendService;
  orderTicketSectionAdminService: OrderTicketSectionAdminService;
  orderTicketSectionFrontendService: OrderTicketSectionFrontendService;
  foodMenuFrontendService: FoodMenuFrontendService;
  foodMenuAdminService: FoodMenuAdminService;
  paymentFrontendService: PaymentFrontendService;
  paymentAdminService: PaymentAdminService;
  orderFrontendService: OrderFrontendService;
  orderAdminService: OrderAdminService;
  uploadFrontendService: UploadFrontendService;
  uploadAdminService: UploadAdminService;
  settingsService: SettingsService;
  dashboardAdminService: DashboardAdminService;
  commentAdminService: CommentAdminService;
  commentService: CommentFrontendService;
  reviewAdminService: AdminReviewService;
  reviewService: FrontendReviewService;
  siteStatisticsAdmin: ISiteStatisticsAdminService;
  siteStatisticsFrontend: ISiteStatisticsFrontendService;
  mailService: MailService;
  adminMenuAdminService: AdminMenuAdminService;
  adminMenuFrontendService: AdminMenuFrontendService;
  
  // Grouped services
  admin: {
    review: AdminReviewService;
    comment: CommentAdminService;
    user: UserAdminService;
    post: PostAdminService;
    settings: SettingsAdminService;
    seo: SeoAdminService;
    footer: FooterAdminService;
    category: CategoryAdminService;
    service: ServiceAdminService;
    product: ProductAdminService;
    featureFlags: FeatureFlagsAdminService;
    theme: ThemeAdminService;
    themeSection: ThemeSectionAdminService;
    componentStyleConfig: ComponentStyleConfigAdminService;
    language: LanguageAdminService;
    about: AboutAdminService;
    logo: LogoAdminService;
    customerLogo: CustomerLogoAdminService;
    auth: AuthAdminService;
    contact: ContactAdminService;
    contactSection: ContactSectionAdminService;
    ticketPricingSection: TicketPricingSectionAdminService;
    foodMenu: FoodMenuAdminService;
    payment: PaymentAdminService;
    order: OrderAdminService;
    upload: UploadAdminService;
    orderTicketSection: OrderTicketSectionAdminService;
    dashboard: DashboardAdminService;
    gallery: GalleryAdminService;
    adminMenu: AdminMenuAdminService;
  };
  
  frontend: {
    review: FrontendReviewService;
    comment: CommentFrontendService;
    post: PostFrontendService;
    settings: SettingsFrontendService;
    seo: SeoFrontendService;
    footer: FooterFrontendService;
    category: CategoryFrontendService;
    service: ServiceFrontendService;
    product: ProductFrontendService;
    featureFlags: FeatureFlagsFrontendService;
    theme: ThemeFrontendService;
    componentStyleConfig: ComponentStyleConfigFrontendService;
    language: LanguageFrontendService;
    about: AboutFrontendService;
    logo: LogoFrontendService;
    customerLogo: CustomerLogoFrontendService;
    auth: AuthFrontendService;
    contact: ContactFrontendService;
    contactSection: ContactSectionFrontendService;
    ticketPricingSection: TicketPricingSectionFrontendService;
    foodMenu: FoodMenuFrontendService;
    payment: PaymentFrontendService;
    order: OrderFrontendService;
    upload: UploadFrontendService;
    orderTicketSection: OrderTicketSectionFrontendService;
    gallery: GalleryFrontendService;
    adminMenu: AdminMenuFrontendService;
  };
} 