import { UserService } from '../../user/services/user.service';
import { PostFrontendService } from '../../post/frontend/services/post-frontend.service';
import { PostAdminService } from '../../post/admin/services/post-admin.service';
import { ProfileService } from '../../profile/services/profile.service';
import { SettingsAdminService } from '../../settings/admin/services/settings-admin.service';
import { SettingsFrontendService } from '../../settings/frontend/services/settings-frontend.service';
import { SeoAdminService } from '../../seo/admin/services/seo-admin.service';
import { SeoFrontendService } from '../../seo/frontend/services/seo-frontend.service';
import { FooterAdminService } from '../../footer/admin/services/footer-admin.service';
import { FooterFrontendService } from '../../footer/frontend/services/footer-frontend.service';
import { CategoryFrontendService } from '../../category/frontend/services/category-frontend.service';
import { CategoryAdminService } from '../../category/admin/services/category-admin.service';
import { ServiceAdminService } from '../../service/admin/services/service-admin.service';
import { ServiceFrontendService } from '../../service/frontend/services/service-frontend.service';
import { ProductAdminService } from '../../product/admin/services/product-admin.service';
import { ProductFrontendService } from '../../product/frontend/services/product-frontend.service';
import { CrossSellService } from '../../product/frontend/services/cross-sell.service';
import { ProductSpecificationService } from '../../product/services/product-specification.service';
import { ProductComboService } from '../../product/frontend/services/product-combo.service';
import { PriceRequestService } from '../../price-request/services/price-request.service';
import { FeatureFlagsAdminService } from '../../feature-flags/admin/services/feature-flags-admin.service';
import { FeatureFlagsFrontendService } from '../../feature-flags/frontend/services/feature-flags-frontend.service';
import { HeroService } from '../../hero/admin/services/hero.service';
import { HeroSliderService } from '../../hero/admin/services/hero-slider.service';
import { HeroVideoService } from '../../hero/services/hero-video.service';
import { ThemeAdminService } from '../../theme/admin/services/theme-admin.service';
import { ThemeFrontendService } from '../../theme/frontend/services/theme-frontend.service';
import { ComponentStyleConfigAdminService } from '../../theme/admin/services/component-style-config-admin.service';
import { ComponentStyleConfigFrontendService } from '../../theme/frontend/services/component-style-config-frontend.service';
import { LanguageFrontendService } from '../../language/frontend/services/language-frontend.service';
import { LanguageAdminService } from '../../language/admin/services/language-admin.service';
import { AboutAdminService } from '../../about/admin/services/about-admin.service';
import { AboutFrontendService } from '../../about/frontend/services/about-frontend.service';
import { LogoFrontendService } from '../../settings/frontend/services/logo-frontend.service';
import { LogoAdminService } from '../../settings/admin/services/logo-admin.service';
import { CustomerLogoFrontendService } from '../../customer-logo/frontend/services/customer-logo-frontend.service';
import { CustomerLogoAdminService } from '../../customer-logo/admin/services/customer-logo-admin.service';
import { AuthFrontendService } from '../../auth/frontend/services/auth-frontend.service';
import { AuthAdminService } from '../../auth/admin/services/auth-admin.service';
import { ContactAdminService } from '../../contact/admin/services/contact-admin.service';
import { ContactFrontendService } from '../../contact/frontend/services/contact-frontend.service';
import { GalleryFrontendService } from '../../gallery/frontend/services/gallery-frontend.service';
import { ContactSectionAdminService } from '../../contact/admin/services/contact-section-admin.service';
import { ContactSectionFrontendService } from '../../contact/frontend/services/contact-section-frontend.service';
import { TicketPricingSectionAdminService } from '../../ticket-pricing/admin/services/ticket-pricing-section-admin.service';
import { TicketPricingSectionFrontendService } from '../../ticket-pricing/frontend/services/ticket-pricing-section-frontend.service';

export interface ITrpcServices {
  userService: UserService;
  postService: PostFrontendService;
  postAdminService: PostAdminService;
  profileService: ProfileService;
  settingsAdminService: SettingsAdminService;
  settingsFrontendService: SettingsFrontendService;
  seoAdminService: SeoAdminService;
  seoFrontendService: SeoFrontendService;
  footerAdminService: FooterAdminService;
  footerFrontendService: FooterFrontendService;
  categoryFrontendService: CategoryFrontendService;
  categoryAdminService: CategoryAdminService;
  serviceAdminService: ServiceAdminService;
  serviceFrontendService: ServiceFrontendService;
  productAdminService: ProductAdminService;
  productFrontendService: ProductFrontendService;
  crossSellService: CrossSellService;
  productSpecificationService: ProductSpecificationService;
  productComboService: ProductComboService;
  priceRequestService: PriceRequestService;
  featureFlagsAdminService: FeatureFlagsAdminService;
  featureFlagsFrontendService: FeatureFlagsFrontendService;
  heroService: HeroService;
  heroSliderService: HeroSliderService;
  heroVideoService: HeroVideoService;
  themeAdminService: ThemeAdminService;
  themeFrontendService: ThemeFrontendService;
  componentStyleConfigAdminService: ComponentStyleConfigAdminService;
  componentStyleConfigFrontendService: ComponentStyleConfigFrontendService;
  languageFrontendService: LanguageFrontendService;
  languageAdminService: LanguageAdminService;
  aboutAdminService: AboutAdminService;
  aboutFrontendService: AboutFrontendService;
  logoFrontendService: LogoFrontendService;
  logoAdminService: LogoAdminService;
  customerLogoFrontendService: CustomerLogoFrontendService;
  customerLogoAdminService: CustomerLogoAdminService;
  authFrontendService: AuthFrontendService;
  authAdminService: AuthAdminService;
  contactAdminService: ContactAdminService;
  contactFrontendService: ContactFrontendService;
  galleryFrontendService: GalleryFrontendService;
  contactSectionAdminService: ContactSectionAdminService;
  contactSectionFrontendService: ContactSectionFrontendService;
  ticketPricingSectionAdminService: TicketPricingSectionAdminService;
  ticketPricingSectionFrontendService: TicketPricingSectionFrontendService;
} 