export const Permissions = {
  // User permissions
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USERS: 'CREATE_USERS',
  EDIT_USERS: 'EDIT_USERS',
  DELETE_USERS: 'DELETE_USERS',

  // Content permissions
  VIEW_CONTENT: 'VIEW_CONTENT',
  CREATE_CONTENT: 'CREATE_CONTENT',
  EDIT_CONTENT: 'EDIT_CONTENT',
  DELETE_CONTENT: 'DELETE_CONTENT',
  PUBLISH_CONTENT: 'PUBLISH_CONTENT',

  // Dashboard permissions
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_DASHBOARD: 'MANAGE_DASHBOARD',

  // Role Management
  VIEW_ROLES: 'VIEW_ROLES',
  CREATE_ROLES: 'CREATE_ROLES',
  EDIT_ROLES: 'EDIT_ROLES',
  DELETE_ROLES: 'DELETE_ROLES',

  // Settings Management
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  EDIT_SETTINGS: 'EDIT_SETTINGS',

  // Menu Management
  VIEW_MENUS: 'VIEW_MENUS',
  CREATE_MENUS: 'CREATE_MENUS',
  EDIT_MENUS: 'EDIT_MENUS',
  DELETE_MENUS: 'DELETE_MENUS',

  // Ticket Management
  VIEW_TICKETS: 'VIEW_TICKETS',
  SCAN_TICKETS: 'SCAN_TICKETS',
  VIEW_SCAN_HISTORY: 'VIEW_SCAN_HISTORY',
  SEARCH_TICKETS: 'SEARCH_TICKETS',
  MANAGE_TICKETS: 'MANAGE_TICKETS',

  // Add other permissions as needed...
} as const; 